ZORDER_INDOOR_MAP_BACKGROUD = 0
ZORDER_PLOT_WHITE_BACKGROUND = 1
ZORDER_PLOT_GRID = 2
ZORDER_PLOT_ROUTE = 3
ZORDER_PLOT_CELL = 4
ZORDER_PLOT_PARAM_START = 10
ZORDER_PLOT_CELL_LABEL = 20
ZORDER_PLOT_GRID_LABEL = 21
